spring:
  datasource:
    url: jdbc:h2:mem:notification_test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecommerce.notificationservice.event"
        spring.json.value.default.type: com.ecommerce.notificationservice.event.PaymentCompletedEvent
        spring.json.use.type.headers: false

eureka:
  client:
    enabled: false

logging:
  level:
    root: ERROR
    kafka: ERROR
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR