server:
  port: 8086

spring:
  application:
    name: inventory-service
  cloud:
    openfeign:
      client:
        config:
          product-service:
            connectTimeout: 3000
            readTimeout: 5000

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: tiger
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.example.orderservice.dto.OrderCreatedEvent:com.ecommerce.inventoryservice.dto.OrderCreatedEvent,com.example.orderservice.dto.OrderCancelledEvent:com.ecommerce.inventoryservice.dto.OrderCancelledEvent

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info